### ISSUE TITLE
项目引用了com.alibaba:fastjson@1.2.47等23个开源组件，存在4个漏洞，建议升级

### ISSUE THREAD

**Issue by Abbykawai** [MrDemonlxl/mylearnproject#1]
大佬，看你这个项目调用了com.alibaba:fastjson@1.2.47等23个开源组件，存在4个安全漏洞，建议你升级下。
```
漏洞标题：Fastjson 1.2.25-1.2.47版本远程代码执行漏洞
漏洞编号：
漏洞描述：
Fastjson 是Java语言实现的快速JSON解析和生成器，在1.2.25-1.2.47版本中攻击者可通过精心构造的JSON请求，绕过此前修复机制，远程执行任意代码。
漏洞原因：
攻击者可通过白名单类java.lang.Class绕过checkAutotype方法，利用fastjson的cache机制引入恶意类，并调用连接远程rmi主机，通过其中的恶意类执行代码。
漏洞级别：严重
影响范围：[1.2.25, 1.2.48)
最小修复版本：1.2.48
引入路径：
pers.lxl:mylearnproject:0.0.1-SNAPSHOT:->pers.lxl:mylearnproject@0.0.1-SNAPSHOT->com.alibaba:fastjson@1.2.47
```
另外3个漏洞 ，信息有点多我就不贴了，你自己看下完整报告：https://www.mfsec.cn/jr?p=i996d8

**Comment by MrDemonlxl** [comment]
> @MrDemonlxl 大佬，你这个项目还在维护吗？有空辛苦处理下这个问题哈，有什么问题可以随时联系我。

感谢关注项目漏洞，已将fastjson版本升级至1.2.76。

**Comment by Abbykawai** [comment]
辛苦啦

**Comment by MrDemonlxl** [comment]
可以加个联系方式吗，咨询一个问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月22日(周二) 晚上8:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MrDemonlxl/mylearnproject] ***@***.***等23个开源组件，存在4个漏洞，建议升级 (Issue #1)




 
辛苦啦
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Abbykawai** [comment]
好的，您留个邮箱？我给您发邮件

**Comment by MrDemonlxl** [comment]
***@***.***



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月22日(周二) 晚上9:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MrDemonlxl/mylearnproject] ***@***.***等23个开源组件，存在4个漏洞，建议升级 (Issue #1)




 
好的，您留个邮箱？我给您发邮件
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
